require("user.plugins.impatient")
require("user.plugins-setup")
require("user.core.options")
require("user.core.keymaps")
require("user.core.colorscheme")
-- require("user.plugins.comment")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.telescope")
require("user.plugins.cmp")
require("user.plugins.lsp")
require("user.plugins.treesitter")
require("user.plugins.autopairs")
require("user.plugins.bufferline")
require("user.plugins.project")
require("user.plugins.alpha")
require("user.plugins.indentline")
